name: PHPStan

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - .:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
      - name: PHPStan
        run: |
          ./vendor/bin/phpstan analyse --ansi
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@feature/add-commit-id
        if: always()
        with:
          channel: CEWJP77BP
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
